In [1]:
# 加载所需要的包
%matplotlib inline

# scitnific computing and plotting
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
import seaborn as sns

# HDDM related packages
import pymc as pm
import hddm
import kabuki
import arviz as az
print("The current HDDM version is: ", hddm.__version__)
print("The current kabuki version is: ", kabuki.__version__)
print("The current PyMC version is: ", pm.__version__)
print("The current ArviZ version is: ", az.__version__)

import warnings
warnings.filterwarnings('ignore')

The current HDDM version is:  1.0.1RC
The current kabuki version is:  0.6.5RC4
The current PyMC version is:  2.3.8
The current ArviZ version is:  0.15.1

## 加载数据

In [ ]:
# 读取数据并进行预处理，response=choice
data_motion = hddm.load_csv('../../../3_Data/exp1/CleanData/data_motion.csv')
data_color = hddm.load_csv('../../../3_Data/exp1/CleanData/data_color.csv')

# 提取出不同任务的数据
data_motion_match = data_motion[data_motion['part'] == 'match_RDK'] 
data_motion_rdk = data_motion[data_motion['part'] == 'RDK']
data_color_match = data_color[data_color['part'] == 'match_RDK'] 
data_color_rdk = data_color[data_color['part'] == 'RDK']

data_motion_match = data_motion_match.assign(
    correct=data_motion_match['correct'].astype(int),
    response=data_motion_match['response'].map({'f': 1, 'j': 0, 'arrowleft': 1, 'arrowright': 0}),
    stim2=data_motion_match['isMatch'].map({'match': 1, 'mismatch': 0}), # 这里进行了修改（z flip需要）
    stim=data_motion_match['isMatch'].map({'match': 1, 'mismatch': -1})
)

data_motion_rdk = data_motion_rdk.assign(
    correct=data_motion_rdk['correct'].astype(int),
    response=data_motion_rdk['response'].map({'f': 1, 'j': 0, 'arrowleft': 1, 'arrowright': 0}),
    coherent_direction=data_motion_rdk['coherent_direction'].replace(180, 1), # 左为1
    stim = data_motion_rdk['coherent_direction'].map({180:1, 0:0})

)

data_color_match = data_color_match.assign(
    correct=data_color_match['correct'].astype(int),
    response=data_color_match['response'].map({'f': 1, 'j': 0}),
    stim2=data_color_match['isMatch'].map({'match': 1, 'mismatch': 0}),
    stim=data_color_match['isMatch'].map({'match': 1, 'mismatch': -1})
)

data_color_rdk = data_color_rdk.assign(
    correct=data_color_rdk['correct'].astype(int),
    response=data_color_rdk['response'].map({'f': 1, 'j': 0, 'd': 1, 'k': 0}),
    stim=data_color_rdk['dot_color_final'].map({'["hsl(225, 50%, 50%)","hsl(0, 50%, 50%)"]':0, '["hsl(0, 50%, 50%)","hsl(225, 50%, 50%)"]':1}), # 红为1，蓝为0
)

# 新填choice列，方便后面转换编码方式
data_motion_rdk['choice'] = data_motion_rdk['response']
data_color_rdk['choice'] = data_color_rdk['response']
data_motion_match['choice'] = data_motion_match['response']
data_color_match['choice'] = data_color_match['response']


# data_match
data_color_match

,subj_idx,rt,correct,coherence,part,response,dot_color_final,isMatch,association,difficulty,stim,choice
0,100,1.397,0,0.0,match_RDK,0,"[""hsl(0, 50%, 50%)"",""hsl(225, 50%, 50%)""]",match,self,3,1,0
1,100,1.224,1,0.0,match_RDK,0,"[""hsl(225, 50%, 50%)"",""hsl(0, 50%, 50%)""]",mismatch,other,1,-1,0
2,100,1.123,0,0.0,match_RDK,1,"[""hsl(225, 50%, 50%)"",""hsl(0, 50%, 50%)""]",mismatch,other,2,-1,1
3,100,1.599,1,0.0,match_RDK,0,"[""hsl(225, 50%, 50%)"",""hsl(0, 50%, 50%)""]",mismatch,other,4,-1,0
4,100,1.227,1,0.0,match_RDK,1,"[""hsl(225, 50%, 50%)"",""hsl(0, 50%, 50%)""]",match,other,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
40801,99,1.472,1,0.0,match_RDK,1,"[""hsl(225, 50%, 50%)"",""hsl(0, 50%, 50%)""]",match,other,4,1,1
40802,99,1.408,0,0.0,match_RDK,0,"[""hsl(0, 50%, 50%)"",""hsl(225, 50%, 50%)""]",match,self,3,1,0
40803,99,1.186,1,0.0,match_RDK,0,"[""hsl(225, 50%, 50%)"",""hsl(0, 50%, 50%)""]",mismatch,other,2,-1,0
40804,99,1.504,1,0.0,match_RDK,0,"[""hsl(0, 50%, 50%)"",""hsl(225, 50%, 50%)""]",mismatch,self,2,-1,0
40805,99,2.948,0,0.0,match_RDK,0,"[""hsl(0, 50%, 50%)"",""hsl(225, 50%, 50%)""]",match,self,4,1,0

## 运动组-匹配任务

采用回归模型，设置参数翻转
- m0：基础模型，仅包含a,v,t,z和dc四个参数
- m1：v随matchness和association变化，z随association变化
- m2：v随matchness和association变化，dc随associaition变化，z随association变化
- m3：v随matchness，association和difficulty变化，z随association变化
- m4：v随matchness，association和difficulty变化，dc随associaition变化，z随association变化

注：m1和m3中不包含dc

### m0：仅包含a,v,t,z和dc

**choice coding + v flip，有dc**

In [ ]:
data_motion_match['response'] = data_motion_match['choice']
    
# 构建回归模型
model_reg = [
    {'model': "v ~ 1 + stim", 'link_func': lambda x: x}
] 
 
match_task_motion_m0 = hddm.HDDMRegressor(
    data_motion_match,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    group_only_regressors=False
)

match_task_motion_m0_idata = match_task_motion_m0.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'match_task_motion_m0.db', db = 'pickle')
match_task_motion_m0.save('match_task_motion_m0.hddm')

In [ ]:
summary = az.summary(match_task_motion_m0_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

### m1：v随matchness和association变化，z随association变化

**accuracy coding + z flip，无dc**

In [ ]:
data_motion_match['response'] = data_motion_match['correct']

# 定义链接函数
def z_link_func(x, data=data_motion_match):
    stim = data.stim2.loc[x.index] # 数据中的stim2编码为1和0
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip
    
# 构建回归模型
model_reg = [
    {'model': "z ~ 1", 'link_func': z_link_func},
    {'model': "v ~ 1 + association*isMatch", 'link_func': lambda x: x}
] 
 
match_task_motion_m1 = hddm.HDDMRegressor(
    data_motion_match,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    depends_on={'z': ['association']},
    group_only_regressors=False
)

match_task_motion_m1_idata = match_task_motion_m1.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'match_task_motion_m1.db', db = 'pickle')
match_task_motion_m1.save('match_task_motion_m1.hddm')

In [4]:
summary = az.summary(match_task_motion_m1_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                                                mean     sd  hdi_3%  hdi_97%
a                                              2.075  0.027   2.027    2.127  \
a_std                                          0.218  0.021   0.180    0.258
t                                              0.865  0.029   0.812    0.920
t_std                                          0.241  0.022   0.202    0.282
z_Intercept(other)                             0.517  0.002   0.512    0.521
z_Intercept(self)                              0.521  0.002   0.517    0.525
z_Intercept_std                                0.012  0.002   0.010    0.015
v_Intercept                                    0.471  0.032   0.410    0.529
v_Intercept_std                                0.232  0.025   0.188    0.282
v_association[T.self]                          0.047  0.050  -0.049    0.139
v_association[T.self]_std                      0.370  0.036   0.307    0.438
v_isMatch[T.mismatch]                          0.084  0.037   0.014    0.152
v_isMatch[T.mismatch]_std                      0.228  0.029   0.175    0.281
v_association[T.self]:isMatch[T.mismatch]     -0.017  0.037  -0.086    0.051
v_association[T.self]:isMatch[T.mismatch]_std  0.151  0.049   0.047    0.239

                                               mcse_mean  mcse_sd  ess_bulk
a                                                  0.000    0.000    4569.0  \
a_std                                              0.000    0.000    3231.0
t                                                  0.000    0.000    4442.0
t_std                                              0.000    0.000    4411.0
z_Intercept(other)                                 0.000    0.000     994.0
z_Intercept(self)                                  0.000    0.000    1125.0
z_Intercept_std                                    0.000    0.000     505.0
v_Intercept                                        0.001    0.001    1753.0
v_Intercept_std                                    0.001    0.000    1639.0
v_association[T.self]                              0.001    0.001    1902.0
v_association[T.self]_std                          0.001    0.001    2234.0
v_isMatch[T.mismatch]                              0.001    0.001     753.0
v_isMatch[T.mismatch]_std                          0.001    0.001    1063.0
v_association[T.self]:isMatch[T.mismatch]          0.002    0.001     410.0
v_association[T.self]:isMatch[T.mismatch]_std      0.005    0.004     107.0

                                               ess_tail  r_hat
a                                                4415.0   1.00
a_std                                            3746.0   1.00
t                                                4354.0   1.00
t_std                                            4435.0   1.00
z_Intercept(other)                               2310.0   1.00
z_Intercept(self)                                2768.0   1.00
z_Intercept_std                                  1171.0   1.00
v_Intercept                                      3789.0   1.00
v_Intercept_std                                  2448.0   1.01
v_association[T.self]                            4311.0   1.00
v_association[T.self]_std                        3805.0   1.00
v_isMatch[T.mismatch]                            1794.0   1.00
v_isMatch[T.mismatch]_std                        1905.0   1.00
v_association[T.self]:isMatch[T.mismatch]         955.0   1.01
v_association[T.self]:isMatch[T.mismatch]_std      65.0   1.03

### m2: v随matchness和association变化，dc随associaition变化，z随association变化

**choice coding + v flip，有dc**

In [ ]:
data_motion_match['response'] = data_motion_match['choice']

# 构建回归模型
model_reg = [
    {'model': "v ~ 1 + association*stim", 'link_func': lambda x: x}
] 
 
match_task_motion_m2 = hddm.HDDMRegressor(
    data_motion_match,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    depends_on={'z': ['association']},
    group_only_regressors=False
)

match_task_motion_m2_idata = match_task_motion_m2.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'match_task_motion_m2.db', db = 'pickle')
match_task_motion_m2.save('match_task_motion_m2.hddm')

In [6]:
summary = az.summary(match_task_motion_m2_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                                 mean     sd  hdi_3%  hdi_97%  mcse_mean
a                               2.074  0.027   2.022    2.124      0.000  \
a_std                           0.217  0.021   0.179    0.255      0.000
t                               0.872  0.028   0.819    0.923      0.000
t_std                           0.241  0.022   0.201    0.282      0.000
z(other)                        0.534  0.005   0.525    0.542      0.000
z(self)                         0.566  0.005   0.557    0.574      0.000
z_std                           0.107  0.013   0.084    0.132      0.001
v_Intercept                    -0.043  0.019  -0.076   -0.006      0.001
v_Intercept_std                 0.113  0.015   0.086    0.140      0.000
v_association[T.self]          -0.048  0.021  -0.085   -0.006      0.001
v_association[T.self]_std       0.080  0.025   0.033    0.127      0.002
v_stim                          0.479  0.031   0.422    0.539      0.000
v_stim_std                      0.244  0.024   0.201    0.290      0.000
v_association[T.self]:stim      0.022  0.045  -0.065    0.108      0.001
v_association[T.self]:stim_std  0.361  0.034   0.301    0.427      0.001

                                mcse_sd  ess_bulk  ess_tail  r_hat
a                                 0.000    4803.0    4706.0   1.00
a_std                             0.000    3579.0    4062.0   1.00
t                                 0.000    4466.0    4475.0   1.00
t_std                             0.000    4014.0    4079.0   1.00
z(other)                          0.000     912.0    2423.0   1.00
z(self)                           0.000    1181.0    2781.0   1.00
z_std                             0.000     562.0     986.0   1.00
v_Intercept                       0.000     881.0    1948.0   1.00
v_Intercept_std                   0.000    1261.0    2084.0   1.01
v_association[T.self]             0.001     457.0    1087.0   1.01
v_association[T.self]_std         0.002     139.0      61.0   1.04
v_stim                            0.000    4483.0    5393.0   1.00
v_stim_std                        0.000    2400.0    3358.0   1.00
v_association[T.self]:stim        0.000    4488.0    5280.0   1.00
v_association[T.self]:stim_std    0.000    2748.0    3557.0   1.00

### m3: v随matchness，association和difficulty变化，z随association变化

**accuracy coding + z flip，无dc**

In [ ]:
data_motion_match['response'] = data_motion_match['correct']

# 定义链接函数
def z_link_func(x, data=data_motion_match):
    stim = data.stim2.loc[x.index]
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip
    
# 构建回归模型
model_reg = [
    {'model': "z ~ 1", 'link_func': z_link_func},
    {'model': "v ~ 1 + association*isMatch*difficulty", 'link_func': lambda x: x}
] 
 
match_task_motion_m3 = hddm.HDDMRegressor(
    data_motion_match,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    depends_on={'z': ['association']},
    group_only_regressors=False
)

match_task_motion_m3_idata = match_task_motion_m3.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'match_task_motion_m3.db', db = 'pickle')
match_task_motion_m3.save('match_task_motion_m3.hddm')

In [ ]:
summary = az.summary(match_task_motion_m3_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                                                     mean     sd  hdi_3%
a                                                   2.095  0.028   2.042  \
a_std                                               0.225  0.021   0.187
t                                                   0.863  0.028   0.809
t_std                                               0.241  0.022   0.200
z_Intercept(other)                                  0.517  0.002   0.513
z_Intercept(self)                                   0.522  0.002   0.518
z_Intercept_std                                     0.013  0.001   0.010
v_Intercept                                         0.910  0.047   0.823
v_Intercept_std                                     0.253  0.030   0.201
v_association[T.self]                               0.235  0.071   0.106
v_association[T.self]_std                           0.403  0.044   0.322
v_isMatch[T.mismatch]                              -0.016  0.057  -0.119
v_isMatch[T.mismatch]_std                           0.226  0.030   0.171
v_association[T.self]:isMatch[T.mismatch]          -0.117  0.071  -0.271
v_association[T.self]:isMatch[T.mismatch]_std       0.074  0.057   0.002
v_difficulty                                       -0.169  0.013  -0.195
v_difficulty_std                                    0.032  0.012   0.009
v_association[T.self]:difficulty                   -0.070  0.020  -0.109
v_association[T.self]:difficulty_std                0.065  0.017   0.030
v_isMatch[T.mismatch]:difficulty                    0.039  0.018   0.002
v_isMatch[T.mismatch]:difficulty_std                0.016  0.012   0.000
v_association[T.self]:isMatch[T.mismatch]:diffi...  0.037  0.025  -0.007
v_association[T.self]:isMatch[T.mismatch]:diffi...  0.061  0.014   0.037

                                                    hdi_97%  mcse_mean
a                                                     2.147      0.000  \
a_std                                                 0.264      0.000
t                                                     0.917      0.000
t_std                                                 0.280      0.000
z_Intercept(other)                                    0.521      0.000
z_Intercept(self)                                     0.526      0.000
z_Intercept_std                                       0.016      0.000
v_Intercept                                           0.996      0.011
v_Intercept_std                                       0.309      0.001
v_association[T.self]                                 0.373      0.015
v_association[T.self]_std                             0.486      0.002
v_isMatch[T.mismatch]                                 0.097      0.017
v_isMatch[T.mismatch]_std                             0.279      0.001
v_association[T.self]:isMatch[T.mismatch]            -0.004      0.027
v_association[T.self]:isMatch[T.mismatch]_std         0.171      0.016
v_difficulty                                         -0.146      0.004
v_difficulty_std                                      0.052      0.002
v_association[T.self]:difficulty                     -0.035      0.006
v_association[T.self]:difficulty_std                  0.094      0.002
v_isMatch[T.mismatch]:difficulty                      0.071      0.006
v_isMatch[T.mismatch]:difficulty_std                  0.039      0.004
v_association[T.self]:isMatch[T.mismatch]:diffi...    0.088      0.009
v_association[T.self]:isMatch[T.mismatch]:diffi...    0.087      0.001

                                                    mcse_sd  ess_bulk
a                                                     0.000    4428.0  \
a_std                                                 0.000    4012.0
t                                                     0.000    4689.0
t_std                                                 0.000    4359.0
z_Intercept(other)                                    0.000     982.0
z_Intercept(self)                                     0.000    1062.0
z_Intercept_std                                       0.000     724.0
v_Intercept                                           0.008      19.0
v_Intercept_std                                       0.001     554.0
v_association[T.self]                                 0.012      22.0
v_association[T.self]_std                             0.001     711.0
v_isMatch[T.mismatch]                                 0.013      11.0
v_isMatch[T.mismatch]_std                             0.001     666.0
v_association[T.self]:isMatch[T.mismatch]             0.021       8.0
v_association[T.self]:isMatch[T.mismatch]_std         0.012      12.0
v_difficulty                                          0.003      12.0
v_difficulty_std                                      0.002      29.0
v_association[T.self]:difficulty                      0.004      13.0
v_association[T.self]:difficulty_std                  0.001     122.0
v_isMatch[T.mismatch]:difficulty                      0.004       9.0
v_isMatch[T.mismatch]:difficulty_std                  0.003       8.0
v_association[T.self]:isMatch[T.mismatch]:diffi...    0.007       9.0
v_association[T.self]:isMatch[T.mismatch]:diffi...    0.001     196.0

                                                    ess_tail  r_hat
a                                                     3542.0   1.00
a_std                                                 4062.0   1.00
t                                                     4243.0   1.00
t_std                                                 3782.0   1.00
z_Intercept(other)                                    2253.0   1.01
z_Intercept(self)                                     2859.0   1.01
z_Intercept_std                                       1062.0   1.01
v_Intercept                                             50.0   1.15
v_Intercept_std                                       1491.0   1.01
v_association[T.self]                                   52.0   1.13
v_association[T.self]_std                             2203.0   1.01
v_isMatch[T.mismatch]                                   19.0   1.30
v_isMatch[T.mismatch]_std                             1421.0   1.01
v_association[T.self]:isMatch[T.mismatch]               17.0   1.44
v_association[T.self]:isMatch[T.mismatch]_std           66.0   1.28
v_difficulty                                            70.0   1.26
v_difficulty_std                                        87.0   1.10
v_association[T.self]:difficulty                        30.0   1.23
v_association[T.self]:difficulty_std                   158.0   1.02
v_isMatch[T.mismatch]:difficulty                        17.0   1.42
v_isMatch[T.mismatch]:difficulty_std                    29.0   1.47
v_association[T.self]:isMatch[T.mismatch]:diffi...      19.0   1.39
v_association[T.self]:isMatch[T.mismatch]:diffi...     493.0   1.03
[-----------------95%----------------  ] 1911 of 2000 complete in 26727.4 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 26740.7 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 26755.9 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 26772.2 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 26786.2 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 26800.2 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 26813.8 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 26827.3 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 26840.7 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 26853.3 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 26866.9 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 26880.8 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 26893.6 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 26906.4 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 26919.5 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 26933.2 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 26945.5 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 26958.2 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 26971.5 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 26984.9 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 27002.3 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 27017.1 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 27030.4 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 27044.5 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 27057.9 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 27070.6 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 27083.3 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 27099.5 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 27113.8 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 27126.5 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 27139.9 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 27153.6 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 27166.9 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 27180.6 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 27193.5 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 27206.4 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 27219.9 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 27233.4 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 27246.7 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 27259.7 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 27273.1 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 27286.8 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 27299.8 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 27312.6 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 27325.5 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 27340.2 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 27353.9 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 27367.2 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 27380.0 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 27393.7 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 27408.9 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 27423.4 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 27437.9 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 27451.7 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 27464.9 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 27478.4 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 27492.1 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 27505.2 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 27519.0 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 27532.6 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 27546.4 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 27559.6 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 27572.1 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 27585.0 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 27599.4 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 27613.0 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 27626.4 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 27639.7 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 27653.0 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 27667.6 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 27679.2 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 27690.9 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 27703.0 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 27714.5 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 27725.8 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 27737.4 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 27748.1 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 27758.8 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 27769.5 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 27779.9 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 27788.7 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 27797.3 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 27805.7 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 27814.3 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 27822.9 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 27831.8 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 27840.4 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 27849.0 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 27857.5 sec
[-----------------100%-----------------] 2000 of 2000 complete in 27865.7 sec
[-----------------100%-----------------] 2001 of 2000 complete in 27874.4 sec
hddm sampling elpased time:  27876.238 s
[-----------------96%----------------  ] 1920 of 2000 complete in 27011.4 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 27026.6 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 27040.7 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 27054.7 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 27068.6 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 27082.1 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 27095.5 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 27111.6 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 27125.8 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 27138.9 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 27152.6 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 27167.3 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 27181.4 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 27195.5 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 27208.8 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 27222.2 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 27236.5 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 27251.3 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 27264.8 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 27278.0 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 27292.1 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 27306.3 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 27319.5 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 27332.7 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 27346.7 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 27361.6 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 27375.3 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 27388.4 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 27401.7 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 27417.0 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 27431.8 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 27446.1 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 27460.6 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 27474.1 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 27487.2 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 27501.0 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 27514.3 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 27527.9 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 27542.0 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 27556.0 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 27569.6 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 27582.3 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 27595.3 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 27609.4 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 27623.6 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 27636.9 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 27650.5 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 27663.7 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 27678.4 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 27690.7 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 27702.9 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 27715.1 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 27727.1 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 27738.9 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 27750.9 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 27761.6 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 27772.9 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 27783.7 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 27793.8 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 27802.6 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 27811.3 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 27819.9 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 27829.0 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 27837.8 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 27847.0 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 27855.6 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 27864.5 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 27873.2 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 27881.8 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 27890.7 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 27899.4 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 27908.2 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 27916.9 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 27925.6 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 27933.4 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 27939.9 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 27946.3 sec

### m4: v随matchness，association和difficulty变化，dc随associaition变化，z随association变化

**choice coding + v flip，有dc**

In [ ]:
data_motion_match['response'] = data_motion_match['choice']

# 构建回归模型
model_reg = [
    {'model': "v ~ 1 + association*stim*difficulty", 'link_func': lambda x: x}
] 
 
match_task_motion_m4 = hddm.HDDMRegressor(
    data_motion_match,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    depends_on={'z': ['association']},
    group_only_regressors=False
)

match_task_motion_m4_idata = match_task_motion_m4.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'match_task_motion_m4.db', db = 'pickle')
match_task_motion_m4.save('match_task_motion_m4.hddm')

In [ ]:
summary = az.summary(match_task_motion_m4_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

[-----------------95%----------------  ] 1915 of 2000 complete in 16364.7 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 16374.4 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 16384.6 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 16392.7 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 16401.4 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 16409.6 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 16418.1 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 16426.3 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 16434.5 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 16443.1 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 16451.8 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 16460.4 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 16469.1 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 16477.8 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 16486.9 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 16495.3 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 16503.7 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 16511.7 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 16520.5 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 16529.0 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 16537.9 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 16546.0 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 16554.5 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 16562.8 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 16571.6 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 16580.2 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 16588.5 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 16596.5 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 16604.7 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 16613.0 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 16621.4 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 16630.6 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 16639.4 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 16647.5 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 16655.7 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 16664.2 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 16673.4 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 16681.8 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 16690.8 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 16700.0 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 16709.0 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 16717.0 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 16725.3 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 16733.6 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 16741.9 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 16750.1 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 16758.3 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 16766.7 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 16774.9 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 16783.0 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 16791.2 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 16799.4 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 16808.1 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 16816.8 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 16824.8 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 16833.2 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 16841.6 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 16850.1 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 16858.3 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 16866.4 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 16874.7 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 16882.9 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 16891.6 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 16900.5 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 16909.1 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 16917.3 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 16926.1 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 16934.0 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 16942.3 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 16951.3 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 16960.3 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 16968.7 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 16977.1 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 16985.6 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 16994.0 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 17002.7 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 17011.6 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 17021.0 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 17029.8 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 17039.6 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 17051.9 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 17062.3 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 17072.5 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 17082.7 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 17093.1 sec
[-----------------100%-----------------] 2000 of 2000 complete in 17102.2 sec
[-----------------100%-----------------] 2001 of 2000 complete in 17111.4 sec
hddm sampling elpased time:  17113.491 s
[-----------------95%----------------  ] 1915 of 2000 complete in 16382.8 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 16391.4 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 16400.0 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 16408.4 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 16416.9 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 16425.0 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 16433.5 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 16442.1 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 16451.0 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 16459.7 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 16468.1 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 16477.2 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 16486.3 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 16494.9 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 16503.3 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 16511.5 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 16520.6 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 16529.2 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 16538.1 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 16546.4 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 16554.7 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 16563.1 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 16571.9 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 16580.9 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 16589.2 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 16597.2 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 16605.1 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 16613.4 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 16621.8 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 16631.3 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 16639.9 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 16648.1 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 16656.2 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 16664.7 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 16673.8 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 16682.2 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 16690.9 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 16700.3 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 16708.8 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 16717.1 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 16725.4 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 16734.0 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 16742.3 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 16750.9 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 16759.6 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 16768.7 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 16777.2 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 16785.6 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 16794.0 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 16802.6 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 16811.3 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 16819.8 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 16828.4 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 16836.6 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 16845.0 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 16853.7 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 16862.4 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 16870.6 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 16878.7 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 16887.3 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 16895.7 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 16904.5 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 16912.8 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 16921.1 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 16929.5 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 16937.6 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 16946.2 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 16954.9 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 16963.3 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 16971.8 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 16980.3 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 16988.6 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 16996.7 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 17005.3 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 17013.8 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 17022.9 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 17031.5 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 17041.4 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 17052.7 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 17063.1 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 17073.1 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 17083.4 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 17093.4 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 17102.8 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 17111.9 sec
[-----------------100%-----------------] 2000 of 2000 complete in 17121.3 sec
[-----------------100%-----------------] 2001 of 2000 complete in 17136.3 sec
hddm sampling elpased time:  17140.613 s
[-----------------95%----------------  ] 1915 of 2000 complete in 16396.1 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 16404.9 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 16413.0 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 16421.4 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 16429.7 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 16438.2 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 16447.0 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 16455.3 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 16463.9 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 16473.0 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 16481.7 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 16490.8 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 16498.6 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 16506.8 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 16515.3 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 16523.9 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 16532.4 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 16541.1 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 16549.5 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 16557.6 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 16565.5 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 16574.1 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 16583.0 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 16591.3 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 16599.7 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 16607.8 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 16616.3 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 16624.9 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 16634.3 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 16642.7 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 16650.6 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 16659.0 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 16667.2 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 16675.8 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 16684.5 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 16692.8 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 16701.7 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 16710.4 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 16718.5 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 16726.8 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 16735.3 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 16743.5 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 16752.3 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 16760.8 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 16769.7 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 16778.2 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 16786.6 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 16794.7 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 16803.3 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 16812.0 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 16820.9 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 16829.2 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 16837.9 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 16845.9 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 16854.7 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 16863.1 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 16871.5 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 16879.5 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 16888.2 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 16897.0 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 16905.8 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 16914.2 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 16922.1 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 16930.4 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 16938.8 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 16947.3 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 16955.9 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 16963.7 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 16972.3 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 16980.7 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 16988.8 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 16996.6 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 17005.3 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 17013.7 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 17023.0 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 17031.7 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 17041.6 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 17052.6 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 17062.6 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 17072.5 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 17082.2 sec

In [11]:
summary = az.summary(match_task_motion_m4_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                                            mean     sd  hdi_3%  hdi_97%
a                                          2.092  0.028   2.037    2.144  \
a_std                                      0.222  0.021   0.182    0.261
t                                          0.872  0.029   0.815    0.923
t_std                                      0.240  0.022   0.202    0.282
z(other)                                   0.534  0.005   0.525    0.543
z(self)                                    0.564  0.005   0.556    0.574
z_std                                      0.108  0.013   0.083    0.131
v_Intercept                                0.005  0.029  -0.047    0.059
v_Intercept_std                            0.094  0.019   0.060    0.131
v_association[T.self]                      0.003  0.036  -0.068    0.067
v_association[T.self]_std                  0.043  0.032   0.001    0.098
v_stim                                     0.864  0.040   0.786    0.937
v_stim_std                                 0.267  0.029   0.216    0.323
v_association[T.self]:stim                 0.152  0.060   0.042    0.264
v_association[T.self]:stim_std             0.395  0.042   0.322    0.477
v_difficulty                              -0.018  0.009  -0.034   -0.001
v_difficulty_std                           0.024  0.008   0.010    0.038
v_association[T.self]:difficulty          -0.017  0.012  -0.042    0.006
v_association[T.self]:difficulty_std       0.025  0.009   0.008    0.042
v_stim:difficulty                         -0.149  0.009  -0.167   -0.132
v_stim:difficulty_std                      0.030  0.012   0.002    0.048
v_association[T.self]:stim:difficulty     -0.048  0.015  -0.077   -0.021
v_association[T.self]:stim:difficulty_std  0.075  0.013   0.052    0.099

                                           mcse_mean  mcse_sd  ess_bulk
a                                              0.000    0.000    4605.0  \
a_std                                          0.000    0.000    3354.0
t                                              0.000    0.000    4551.0
t_std                                          0.000    0.000    4509.0
z(other)                                       0.000    0.000    1048.0
z(self)                                        0.000    0.000    1200.0
z_std                                          0.000    0.000     731.0
v_Intercept                                    0.006    0.005      20.0
v_Intercept_std                                0.001    0.001     203.0
v_association[T.self]                          0.011    0.008      11.0
v_association[T.self]_std                      0.009    0.006      12.0
v_stim                                         0.002    0.002     310.0
v_stim_std                                     0.001    0.001     453.0
v_association[T.self]:stim                     0.003    0.002     371.0
v_association[T.self]:stim_std                 0.001    0.001    1198.0
v_difficulty                                   0.002    0.001      20.0
v_difficulty_std                               0.001    0.001      45.0
v_association[T.self]:difficulty               0.003    0.002      15.0
v_association[T.self]:difficulty_std           0.001    0.001      66.0
v_stim:difficulty                              0.001    0.001     132.0
v_stim:difficulty_std                          0.002    0.001      47.0
v_association[T.self]:stim:difficulty          0.001    0.001     183.0
v_association[T.self]:stim:difficulty_std      0.001    0.001     270.0

                                           ess_tail  r_hat
a                                            3618.0   1.00
a_std                                        3882.0   1.00
t                                            4185.0   1.00
t_std                                        4020.0   1.00
z(other)                                     2288.0   1.00
z(self)                                      2556.0   1.01
z_std                                        1228.0   1.01
v_Intercept                                    94.0   1.13
v_Intercept_std                               377.0   1.02
v_association[T.self]                          49.0   1.26
v_association[T.self]_std                      58.0   1.25
v_stim                                       1135.0   1.01
v_stim_std                                   2216.0   1.01
v_association[T.self]:stim                   1511.0   1.01
v_association[T.self]:stim_std               2329.0   1.00
v_difficulty                                  122.0   1.13
v_difficulty_std                              124.0   1.06
v_association[T.self]:difficulty               54.0   1.19
v_association[T.self]:difficulty_std           40.0   1.06
v_stim:difficulty                             388.0   1.03
v_stim:difficulty_std                          25.0   1.08
v_association[T.self]:stim:difficulty         530.0   1.02
v_association[T.self]:stim:difficulty_std     488.0   1.01

### 模型比较

In [ ]:
# match_task_motion_m1 = hddm.load('match_task_motion_m1.hddm')
# match_task_motion_m2 = hddm.load('match_task_motion_m2.hddm')
# match_task_motion_m3 = hddm.load('match_task_motion_m3.hddm')
# match_task_motion_m4 = hddm.load('match_task_motion_m4.hddm')

In [ ]:
DIC_dict = {
    "m0": match_task_motion_m0.dic,
    "m1": match_task_motion_m1.dic,
    "m2": match_task_motion_m2.dic,
    "m3": match_task_motion_m3.dic,
    "m4": match_task_motion_m4.dic
}

DIC_table = pd.DataFrame.from_dict(DIC_dict, orient="index", columns=["DIC"])
DIC_table["model"] = DIC_table.index
DIC_table = DIC_table[["model", "DIC"]]
DIC_table.sort_values(by=["DIC"], ascending=False)

   model           DIC
m1    m1  72619.251582
m2    m2  72483.313578
m3    m3  71722.486826
m4    m4  71600.449166

## 颜色组-匹配任务

采用回归模型，设置参数翻转
- m0：基础模型
- m1：v随matchness和association变化，z随association变化
- m2：v随matchness和association变化，dc随associaition变化，z随association变化
- m3：v随matchness，association和difficulty变化，z随association变化
- m4：v随matchness，association和difficulty变化，dc随associaition变化，z随association变化

### m0：仅包含a, v, t, z和dc

**choice coding + v flip，有dc**

In [ ]:
data_color_match['response'] = data_color_match['choice']
    
# 构建回归模型
model_reg = [
    {'model': "v ~ 1 + stim", 'link_func': lambda x: x}
] 
 
match_task_color_m0 = hddm.HDDMRegressor(
    data_color_match,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    group_only_regressors=False
)

match_task_color_m0_idata = match_task_color_m0.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'match_task_color_m0.db', db = 'pickle')
match_task_color_m0.save('match_task_color_m0.hddm')

In [ ]:
summary = az.summary(match_task_color_m0_idata)
# 只筛选出不含"_subj."的参数行
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

### m1：v随matchness和association变化，z随association变化

**accuracy coding + z flip，无dc**

In [ ]:
data_color_match['response'] = data_color_match['correct']

# 定义链接函数
def z_link_func(x, data=data_color_match):
    stim = data.stim2.loc[x.index]
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip
    
# 构建回归模型
model_reg = [
    {'model': "z ~ 1", 'link_func': z_link_func},
    {'model': "v ~ 1 + association*isMatch", 'link_func': lambda x: x}
] 
 
match_task_color_m1 = hddm.HDDMRegressor(
    data_color_match,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    depends_on={'z': ['association']},
    group_only_regressors=False
)

match_task_color_m1_idata = match_task_color_m1.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'match_task_color_m1.db', db = 'pickle')
match_task_color_m1.save('match_task_color_m1.hddm')

In [4]:
summary = az.summary(match_task_color_m1_idata)
# 只筛选出不含"_subj."的参数行
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                                                mean     sd  hdi_3%  hdi_97%
a                                              1.966  0.027   1.915    2.018  \
a_std                                          0.223  0.021   0.183    0.259
t                                              0.681  0.016   0.651    0.711
t_std                                          0.133  0.012   0.111    0.156
z_Intercept(other)                             0.519  0.002   0.514    0.523
z_Intercept(self)                              0.528  0.002   0.523    0.532
z_Intercept_std                                0.015  0.001   0.012    0.017
v_Intercept                                    0.703  0.041   0.627    0.781
v_Intercept_std                                0.321  0.031   0.265    0.379
v_association[T.self]                          0.039  0.079  -0.110    0.186
v_association[T.self]_std                      0.629  0.056   0.521    0.732
v_isMatch[T.mismatch]                          0.282  0.037   0.218    0.354
v_isMatch[T.mismatch]_std                      0.208  0.028   0.157    0.263
v_association[T.self]:isMatch[T.mismatch]     -0.178  0.039  -0.246   -0.101
v_association[T.self]:isMatch[T.mismatch]_std  0.098  0.049   0.006    0.175

                                               mcse_mean  mcse_sd  ess_bulk
a                                                  0.000    0.000    4231.0  \
a_std                                              0.000    0.000    3190.0
t                                                  0.000    0.000    4873.0
t_std                                              0.000    0.000    4031.0
z_Intercept(other)                                 0.000    0.000    1030.0
z_Intercept(self)                                  0.000    0.000    1508.0
z_Intercept_std                                    0.000    0.000    1162.0
v_Intercept                                        0.001    0.001    2065.0
v_Intercept_std                                    0.001    0.000    2365.0
v_association[T.self]                              0.002    0.001    2553.0
v_association[T.self]_std                          0.001    0.001    3346.0
v_isMatch[T.mismatch]                              0.002    0.001     390.0
v_isMatch[T.mismatch]_std                          0.001    0.001     825.0
v_association[T.self]:isMatch[T.mismatch]          0.003    0.002     153.0
v_association[T.self]:isMatch[T.mismatch]_std      0.012    0.008      18.0

                                               ess_tail  r_hat
a                                                4102.0   1.00
a_std                                            4491.0   1.00
t                                                3746.0   1.00
t_std                                            3693.0   1.00
z_Intercept(other)                               2611.0   1.00
z_Intercept(self)                                3470.0   1.00
z_Intercept_std                                  1947.0   1.00
v_Intercept                                      4083.0   1.00
v_Intercept_std                                  3489.0   1.00
v_association[T.self]                            5458.0   1.00
v_association[T.self]_std                        4030.0   1.00
v_isMatch[T.mismatch]                            1252.0   1.00
v_isMatch[T.mismatch]_std                        1200.0   1.01
v_association[T.self]:isMatch[T.mismatch]         459.0   1.02
v_association[T.self]:isMatch[T.mismatch]_std      37.0   1.17

### m2: v随matchness和association变化，dc随associaition变化，z随association变化

**choice coding + v flip，有dc**

In [ ]:
data_color_match['response'] = data_color_match['choice']

# 构建回归模型
model_reg = [
    {'model': "v ~ 1 + association*stim", 'link_func': lambda x: x}
] 
 
match_task_color_m2 = hddm.HDDMRegressor(
    data_color_match,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    depends_on={'z': ['association']},
    group_only_regressors=False
)

match_task_color_m2_idata = match_task_color_m2.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'match_task_color_m2.db', db = 'pickle')
match_task_color_m2.save('match_task_color_m2.hddm')

In [6]:
summary = az.summary(match_task_color_m2_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

[-----------------95%----------------  ] 1914 of 2000 complete in 17849.4 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 17858.5 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 17867.0 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 17875.3 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 17883.8 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 17892.4 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 17900.9 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 17909.1 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 17918.5 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 17926.9 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 17935.2 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 17943.7 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 17952.9 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 17961.6 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 17970.4 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 17981.0 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 17989.9 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 17999.0 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 18008.0 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 18016.7 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 18025.3 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 18034.6 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 18043.6 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 18052.1 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 18060.3 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 18067.7 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 18075.6 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 18083.0 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 18090.1 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 18097.6 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 18104.6 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 18111.7 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 18118.4 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 18125.5 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 18132.2 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 18139.9 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 18147.2 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 18154.1 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 18161.3 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 18168.4 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 18175.3 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 18182.7 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 18190.3 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 18197.2 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 18204.6 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 18211.5 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 18218.4 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 18225.8 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 18233.1 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 18240.3 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 18247.8 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 18255.2 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 18262.4 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 18270.1 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 18277.9 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 18285.4 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 18292.3 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 18299.4 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 18307.5 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 18314.7 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 18322.7 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 18330.0 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 18337.5 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 18344.8 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 18353.0 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 18360.5 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 18367.8 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 18375.1 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 18383.4 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 18390.5 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 18399.1 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 18406.4 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 18413.9 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 18421.7 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 18428.7 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 18436.5 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 18444.2 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 18451.5 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 18458.7 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 18466.3 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 18473.9 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 18480.8 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 18487.9 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 18495.4 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 18502.5 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 18509.9 sec
[-----------------100%-----------------] 2000 of 2000 complete in 18517.7 sec
[-----------------100%-----------------] 2001 of 2000 complete in 18525.0 sec
hddm sampling elpased time:  18527.152 s
                                 mean     sd  hdi_3%  hdi_97%  mcse_mean
a                               1.960  0.027   1.907    2.009      0.000  \
a_std                           0.223  0.021   0.186    0.263      0.000
t                               0.691  0.016   0.661    0.720      0.000
t_std                           0.133  0.012   0.111    0.155      0.000
z(other)                        0.531  0.005   0.522    0.541      0.000
z(self)                         0.572  0.005   0.562    0.581      0.000
z_std                           0.133  0.012   0.109    0.155      0.000
v_Intercept                    -0.126  0.019  -0.161   -0.091      0.001
v_Intercept_std                 0.107  0.015   0.078    0.135      0.000
v_association[T.self]           0.021  0.020  -0.016    0.056      0.001
v_association[T.self]_std       0.058  0.029   0.005    0.102      0.008
v_stim                          0.802  0.041   0.725    0.879      0.001
v_stim_std                      0.330  0.031   0.274    0.388      0.001
v_association[T.self]:stim     -0.080  0.074  -0.219    0.057      0.001
v_association[T.self]:stim_std  0.608  0.054   0.513    0.713      0.001

                                mcse_sd  ess_bulk  ess_tail  r_hat
a                                 0.000    4355.0    3956.0   1.00
a_std                             0.000    3910.0    3912.0   1.00
t                                 0.000    4603.0    4533.0   1.00
t_std                             0.000    4518.0    3884.0   1.00
z(other)                          0.000    1070.0    2741.0   1.00
z(self)                           0.000    1769.0    3620.0   1.00
z_std                             0.000    1193.0    1929.0   1.00
v_Intercept                       0.001     485.0    1749.0   1.00
v_Intercept_std                   0.000     952.0    1481.0   1.01
v_association[T.self]             0.001     177.0     426.0   1.02
v_association[T.self]_std         0.006      13.0      26.0   1.23
v_stim                            0.000    4702.0    5382.0   1.00
v_stim_std                        0.000    3030.0    3830.0   1.00
v_association[T.self]:stim        0.001    5136.0    5774.0   1.00
v_association[T.self]:stim_std    0.001    3901.0    3889.0   1.00

### m3: v随matchness，association和difficulty变化，z随association变化

**accuracy coding + z flip, 无dc**

In [ ]:
data_color_match['response'] = data_color_match['correct']

# 定义链接函数
def z_link_func(x, data=data_color_match):
    stim = data.stim.loc[x.index]
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip
    
# 构建回归模型
model_reg = [
    {'model': "z ~ 1", 'link_func': z_link_func},
    {'model': "v ~ 1 + association*isMatch*difficulty", 'link_func': lambda x: x}
] 
 
match_task_color_m3 = hddm.HDDMRegressor(
    data_color_match,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    depends_on={'z': ['association']},
    group_only_regressors=False
)

match_task_color_m3_idata = match_task_color_m3.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'match_task_color_m3.db', db = 'pickle')
match_task_color_m3.save('match_task_color_m3.hddm')

In [8]:
summary = az.summary(match_task_color_m3_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

[-----------------95%----------------  ] 1907 of 2000 complete in 54863.7 sec
[-----------------95%----------------  ] 1908 of 2000 complete in 54885.3 sec
[-----------------95%----------------  ] 1909 of 2000 complete in 54907.1 sec
[-----------------95%----------------  ] 1910 of 2000 complete in 54930.6 sec
[-----------------95%----------------  ] 1911 of 2000 complete in 54952.8 sec
[-----------------95%----------------  ] 1912 of 2000 complete in 54974.1 sec
[-----------------95%----------------  ] 1913 of 2000 complete in 54995.4 sec
[-----------------95%----------------  ] 1914 of 2000 complete in 55016.8 sec
[-----------------95%----------------  ] 1915 of 2000 complete in 55039.0 sec
[-----------------95%----------------  ] 1916 of 2000 complete in 55060.2 sec
[-----------------95%----------------  ] 1917 of 2000 complete in 55081.4 sec
[-----------------95%----------------  ] 1918 of 2000 complete in 55102.8 sec
[-----------------95%----------------  ] 1919 of 2000 complete in 55124.0 sec
[-----------------96%----------------  ] 1920 of 2000 complete in 55145.5 sec
[-----------------96%----------------  ] 1921 of 2000 complete in 55166.9 sec
[-----------------96%----------------  ] 1922 of 2000 complete in 55188.2 sec
[-----------------96%----------------  ] 1923 of 2000 complete in 55209.3 sec
[-----------------96%----------------  ] 1924 of 2000 complete in 55232.7 sec
[-----------------96%----------------  ] 1925 of 2000 complete in 55258.8 sec
[-----------------96%----------------  ] 1926 of 2000 complete in 55284.3 sec
[-----------------96%----------------  ] 1927 of 2000 complete in 55305.6 sec
[-----------------96%----------------  ] 1928 of 2000 complete in 55327.5 sec
[-----------------96%----------------  ] 1929 of 2000 complete in 55349.4 sec
[-----------------96%----------------  ] 1930 of 2000 complete in 55370.3 sec
[-----------------96%----------------  ] 1931 of 2000 complete in 55391.9 sec
[-----------------96%----------------  ] 1932 of 2000 complete in 55412.9 sec
[-----------------96%----------------  ] 1933 of 2000 complete in 55433.9 sec
[-----------------96%----------------  ] 1934 of 2000 complete in 55455.6 sec
[-----------------96%----------------  ] 1935 of 2000 complete in 55477.3 sec
[-----------------96%----------------  ] 1936 of 2000 complete in 55498.1 sec
[-----------------96%----------------  ] 1937 of 2000 complete in 55519.5 sec
[-----------------96%----------------  ] 1938 of 2000 complete in 55541.4 sec
[-----------------96%----------------  ] 1939 of 2000 complete in 55562.2 sec
[-----------------97%----------------  ] 1940 of 2000 complete in 55584.2 sec
[-----------------97%----------------  ] 1941 of 2000 complete in 55605.8 sec
[-----------------97%----------------  ] 1942 of 2000 complete in 55627.7 sec
[-----------------97%----------------  ] 1943 of 2000 complete in 55649.2 sec
[-----------------97%----------------  ] 1944 of 2000 complete in 55670.7 sec
[-----------------97%----------------  ] 1945 of 2000 complete in 55692.5 sec
[-----------------97%----------------  ] 1946 of 2000 complete in 55714.3 sec
[-----------------97%----------------  ] 1947 of 2000 complete in 55736.8 sec
[-----------------97%----------------- ] 1948 of 2000 complete in 55758.0 sec
[-----------------97%----------------- ] 1949 of 2000 complete in 55780.1 sec
[-----------------97%----------------- ] 1950 of 2000 complete in 55802.1 sec
[-----------------97%----------------- ] 1951 of 2000 complete in 55824.0 sec
[-----------------97%----------------- ] 1952 of 2000 complete in 55845.5 sec
[-----------------97%----------------- ] 1953 of 2000 complete in 55866.4 sec
[-----------------97%----------------- ] 1954 of 2000 complete in 55888.1 sec
[-----------------97%----------------- ] 1955 of 2000 complete in 55909.7 sec
[-----------------97%----------------- ] 1956 of 2000 complete in 55931.5 sec
[-----------------97%----------------- ] 1957 of 2000 complete in 55953.1 sec
[-----------------97%----------------- ] 1958 of 2000 complete in 55974.8 sec
[-----------------97%----------------- ] 1959 of 2000 complete in 55996.2 sec
[-----------------98%----------------- ] 1960 of 2000 complete in 56017.5 sec
[-----------------98%----------------- ] 1961 of 2000 complete in 56039.2 sec
[-----------------98%----------------- ] 1962 of 2000 complete in 56060.7 sec
[-----------------98%----------------- ] 1963 of 2000 complete in 56082.4 sec
[-----------------98%----------------- ] 1964 of 2000 complete in 56103.7 sec
[-----------------98%----------------- ] 1965 of 2000 complete in 56127.0 sec
[-----------------98%----------------- ] 1966 of 2000 complete in 56150.3 sec
[-----------------98%----------------- ] 1967 of 2000 complete in 56172.4 sec
[-----------------98%----------------- ] 1968 of 2000 complete in 56195.2 sec
[-----------------98%----------------- ] 1969 of 2000 complete in 56217.1 sec
[-----------------98%----------------- ] 1970 of 2000 complete in 56239.0 sec
[-----------------98%----------------- ] 1971 of 2000 complete in 56260.7 sec
[-----------------98%----------------- ] 1972 of 2000 complete in 56282.2 sec
[-----------------98%----------------- ] 1973 of 2000 complete in 56304.2 sec
[-----------------98%----------------- ] 1974 of 2000 complete in 56325.9 sec
[-----------------98%----------------- ] 1975 of 2000 complete in 56347.5 sec
[-----------------98%----------------- ] 1976 of 2000 complete in 56369.6 sec
[-----------------98%----------------- ] 1977 of 2000 complete in 56392.1 sec
[-----------------98%----------------- ] 1978 of 2000 complete in 56413.9 sec
[-----------------98%----------------- ] 1979 of 2000 complete in 56436.6 sec
[-----------------99%----------------- ] 1980 of 2000 complete in 56458.1 sec
[-----------------99%----------------- ] 1981 of 2000 complete in 56480.2 sec
[-----------------99%----------------- ] 1982 of 2000 complete in 56500.6 sec
[-----------------99%----------------- ] 1983 of 2000 complete in 56519.5 sec
[-----------------99%----------------- ] 1984 of 2000 complete in 56538.1 sec
[-----------------99%----------------- ] 1985 of 2000 complete in 56556.3 sec
[-----------------99%----------------- ] 1986 of 2000 complete in 56574.0 sec
[-----------------99%----------------- ] 1987 of 2000 complete in 56592.3 sec
[-----------------99%----------------- ] 1988 of 2000 complete in 56610.1 sec
[-----------------99%----------------- ] 1989 of 2000 complete in 56627.6 sec
[-----------------99%----------------- ] 1990 of 2000 complete in 56645.5 sec
[-----------------99%----------------- ] 1991 of 2000 complete in 56663.6 sec
[-----------------99%----------------- ] 1992 of 2000 complete in 56681.8 sec
[-----------------99%----------------- ] 1993 of 2000 complete in 56700.5 sec
[-----------------99%----------------- ] 1994 of 2000 complete in 56719.6 sec
[-----------------99%----------------- ] 1995 of 2000 complete in 56738.2 sec
[-----------------99%----------------- ] 1996 of 2000 complete in 56755.8 sec
[-----------------99%----------------- ] 1997 of 2000 complete in 56773.8 sec
[-----------------99%----------------- ] 1998 of 2000 complete in 56791.6 sec
[-----------------99%----------------- ] 1999 of 2000 complete in 56809.1 sec
[-----------------100%-----------------] 2000 of 2000 complete in 56826.8 sec
[-----------------100%-----------------] 2001 of 2000 complete in 56844.6 sec
hddm sampling elpased time:  56850.925 s
                                                     mean     sd  hdi_3%
a                                                   2.039  0.029   1.982  \
a_std                                               0.240  0.023   0.198
t                                                   0.678  0.016   0.648
t_std                                               0.132  0.012   0.109
z_Intercept(other)                                  0.520  0.002   0.516
z_Intercept(self)                                   0.529  0.002   0.525
z_Intercept_std                                     0.015  0.001   0.013
v_Intercept                                         1.778  0.061   1.659
v_Intercept_std                                     0.401  0.041   0.329
v_association[T.self]                               0.248  0.097   0.058
v_association[T.self]_std                           0.636  0.062   0.526
v_isMatch[T.mismatch]                               0.241  0.062   0.126
v_isMatch[T.mismatch]_std                           0.202  0.032   0.143
v_association[T.self]:isMatch[T.mismatch]          -0.461  0.084  -0.622
v_association[T.self]:isMatch[T.mismatch]_std       0.085  0.049   0.002
v_difficulty                                       -0.396  0.015  -0.425
v_difficulty_std                                    0.072  0.011   0.050
v_association[T.self]:difficulty                   -0.081  0.023  -0.125
v_association[T.self]:difficulty_std                0.080  0.016   0.050
v_isMatch[T.mismatch]:difficulty                    0.019  0.019  -0.015
v_isMatch[T.mismatch]:difficulty_std                0.022  0.014   0.001
v_association[T.self]:isMatch[T.mismatch]:diffi...  0.102  0.028   0.061
v_association[T.self]:isMatch[T.mismatch]:diffi...  0.015  0.012   0.000

                                                    hdi_97%  mcse_mean
a                                                     2.090      0.000  \
a_std                                                 0.283      0.000
t                                                     0.707      0.000
t_std                                                 0.155      0.000
z_Intercept(other)                                    0.525      0.000
z_Intercept(self)                                     0.533      0.000
z_Intercept_std                                       0.018      0.000
v_Intercept                                           1.889      0.009
v_Intercept_std                                       0.483      0.002
v_association[T.self]                                 0.427      0.018
v_association[T.self]_std                             0.758      0.002
v_isMatch[T.mismatch]                                 0.358      0.017
v_isMatch[T.mismatch]_std                             0.262      0.002
v_association[T.self]:isMatch[T.mismatch]            -0.332      0.031
v_association[T.self]:isMatch[T.mismatch]_std         0.167      0.007
v_difficulty                                         -0.367      0.003
v_difficulty_std                                      0.092      0.001
v_association[T.self]:difficulty                     -0.040      0.006
v_association[T.self]:difficulty_std                  0.112      0.001
v_isMatch[T.mismatch]:difficulty                      0.055      0.006
v_isMatch[T.mismatch]:difficulty_std                  0.044      0.004
v_association[T.self]:isMatch[T.mismatch]:diffi...    0.153      0.010
v_association[T.self]:isMatch[T.mismatch]:diffi...    0.039      0.003

                                                    mcse_sd  ess_bulk
a                                                     0.000    4464.0  \
a_std                                                 0.000    3310.0
t                                                     0.000    5015.0
t_std                                                 0.000    3636.0
z_Intercept(other)                                    0.000     852.0
z_Intercept(self)                                     0.000    1641.0
z_Intercept_std                                       0.000    1174.0
v_Intercept                                           0.006      46.0
v_Intercept_std                                       0.001     661.0
v_association[T.self]                                 0.013      28.0
v_association[T.self]_std                             0.001    1033.0
v_isMatch[T.mismatch]                                 0.013      14.0
v_isMatch[T.mismatch]_std                             0.001     239.0
v_association[T.self]:isMatch[T.mismatch]             0.024       8.0
v_association[T.self]:isMatch[T.mismatch]_std         0.005      40.0
v_difficulty                                          0.002      27.0
v_difficulty_std                                      0.001     200.0
v_association[T.self]:difficulty                      0.004      16.0
v_association[T.self]:difficulty_std                  0.001     204.0
v_isMatch[T.mismatch]:difficulty                      0.004      11.0
v_isMatch[T.mismatch]:difficulty_std                  0.003      13.0
v_association[T.self]:isMatch[T.mismatch]:diffi...    0.008       9.0
v_association[T.self]:isMatch[T.mismatch]:diffi...    0.002      11.0

                                                    ess_tail  r_hat
a                                                     4422.0   1.00
a_std                                                 3565.0   1.00
t                                                     3946.0   1.00
t_std                                                 4075.0   1.00
z_Intercept(other)                                    2338.0   1.01
z_Intercept(self)                                     3493.0   1.01
z_Intercept_std                                       2105.0   1.00
v_Intercept                                            230.0   1.06
v_Intercept_std                                       2069.0   1.00
v_association[T.self]                                  183.0   1.09
v_association[T.self]_std                             1818.0   1.00
v_isMatch[T.mismatch]                                   43.0   1.21
v_isMatch[T.mismatch]_std                              542.0   1.03
v_association[T.self]:isMatch[T.mismatch]               29.0   1.42
v_association[T.self]:isMatch[T.mismatch]_std           61.0   1.09
v_difficulty                                           127.0   1.11
v_difficulty_std                                       411.0   1.02
v_association[T.self]:difficulty                        81.0   1.19
v_association[T.self]:difficulty_std                   427.0   1.01
v_isMatch[T.mismatch]:difficulty                        47.0   1.27
v_isMatch[T.mismatch]:difficulty_std                    47.0   1.24
v_association[T.self]:isMatch[T.mismatch]:diffi...      22.0   1.40
v_association[T.self]:isMatch[T.mismatch]:diffi...      22.0   1.31

### m4: v随matchness，association和difficulty变化，dc随associaition变化，z随association变化

**choice coding + v flip，有dc**

In [ ]:
data_color_match['response'] = data_color_match['choice']

# 构建回归模型
model_reg = [
    {'model': "v ~ 1 + association*stim*difficulty", 'link_func': lambda x: x}
] 
 
match_task_color_m4 = hddm.HDDMRegressor(
    data_color_match,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    depends_on={'z': ['association']},
    group_only_regressors=False
)

match_task_color_m4_idata = match_task_color_m4.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'match_task_color_m4.db', db = 'pickle')
match_task_color_m4.save('match_task_color_m4.hddm')

In [ ]:
summary = az.summary(match_task_color_m4_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                                            mean     sd  hdi_3%  hdi_97%
a                                          2.033  0.030   1.905    2.143
a_std                                      0.240  0.023   0.175    0.337
t                                          0.687  0.016   0.631    0.759
t_std                                      0.133  0.012   0.095    0.189
z_std                                      0.137  0.012   0.100    0.177
v_Intercept                               -0.116  0.038  -0.248    0.003
v_Intercept_std                            0.083  0.026   0.014    0.172
v_association[T.self]                      0.186  0.053   0.061    0.329
v_association[T.self]_std                  0.052  0.028   0.002    0.164
v_stim                                     1.843  0.057   1.600    2.100
v_stim_std                                 0.412  0.043   0.297    0.633
v_association[T.self]:stim                -0.016  0.081  -0.332    0.285
v_association[T.self]:stim_std             0.606  0.059   0.439    0.882
v_difficulty                              -0.001  0.012  -0.035    0.033
v_difficulty_std                           0.019  0.011   0.000    0.051
v_association[T.self]:difficulty          -0.059  0.017  -0.109   -0.015
v_association[T.self]:difficulty_std       0.011  0.008   0.000    0.042
v_stim:difficulty                         -0.384  0.012  -0.429   -0.342
v_stim:difficulty_std                      0.069  0.011   0.034    0.113
v_association[T.self]:stim:difficulty     -0.027  0.016  -0.083    0.034
v_association[T.self]:stim:difficulty_std  0.081  0.017   0.030    0.152

### 模型比较

In [ ]:
# match_task_color_m1 = hddm.load('match_task_color_m1.hddm')
# match_task_color_m2 = hddm.load('match_task_color_m2.hddm')
# match_task_color_m3 = hddm.load('match_task_color_m3.hddm')
# match_task_color_m4 = hddm.load('match_task_color_m4.hddm')

In [ ]:
DIC_dict = {
    "m0": match_task_color_m0.dic,
    "m1": match_task_color_m1.dic,
    "m2": match_task_color_m2.dic,
    "m3": match_task_color_m3.dic,
    "m4": match_task_color_m4.dic
}

DIC_table = pd.DataFrame.from_dict(DIC_dict, orient="index", columns=["DIC"])
DIC_table["model"] = DIC_table.index
DIC_table = DIC_table[["model", "DIC"]]
DIC_table.sort_values(by=["DIC"], ascending=False)

   model           DIC
m1    m1  61044.607031
m2    m2  60928.043199
m3    m3  57385.039674
m4    m4  57358.463120

## 运动组-辨别任务
- m0：基础模型
- m1: v随association变化
- m2：v随association和difficulty变化

In [17]:
data_motion_rdk

,subj_idx,rt,correct,coherence,part,response,coherent_direction,isMatch,association,difficulty,stim,choice
347,1,0.802,1,0.12,RDK,1,1,NaN,other,1,1,1
348,1,1.213,1,0.08,RDK,1,1,NaN,other,2,1,1
349,1,0.678,1,0.03,RDK,0,0,NaN,self,4,-1,0
350,1,0.878,1,0.03,RDK,1,1,NaN,other,4,1,1
351,1,0.638,1,0.08,RDK,0,0,NaN,self,2,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
38948,9,1.347,1,0.12,RDK,1,1,NaN,other,1,1,1
38949,9,0.773,1,0.09,RDK,1,1,NaN,other,3,1,1
38950,9,0.697,1,0.09,RDK,1,1,NaN,other,2,1,1
38951,9,0.823,1,0.09,RDK,0,0,NaN,self,2,-1,0
38952,9,0.664,0,0.09,RDK,1,0,NaN,self,3,-1,1

### m0

In [ ]:
data_motion_rdk['response'] = data_motion_rdk['correct']

# 定义链接函数
def z_link_func(x, data=data_motion_rdk):
    stim = data.stim.loc[x.index]
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip
    
# 构建回归模型
model_reg = [
    {'model': "z ~ 1", 'link_func': z_link_func},
    {'model': "v ~ 1", 'link_func': lambda x: x}
] 
 
rdk_task_motion_m0 = hddm.HDDMRegressor(
    data_motion_rdk,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    # depends_on={'z': ['association']},
    group_only_regressors=False
)

rdk_task_motion_m0_idata = rdk_task_motion_m0.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'rdk_task_motion_m0.db', db = 'pickle')
rdk_task_motion_m0.save('rdk_task_motion_m0.hddm')

In [ ]:
# 只筛选出不含"_subj."的参数行
summary = az.summary(rdk_task_motion_m0_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

### m1: v随association变化

In [ ]:
data_motion_rdk['response'] = data_motion_rdk['correct']

# 定义链接函数
def z_link_func(x, data=data_motion_rdk):
    stim = data.stim.loc[x.index]
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip
    
# 构建回归模型
model_reg = [
    {'model': "z ~ 1", 'link_func': z_link_func},
    {'model': "v ~ 1 + association", 'link_func': lambda x: x}
] 
 
rdk_task_motion_m1 = hddm.HDDMRegressor(
    data_motion_rdk,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    # depends_on={'z': ['association']},
    group_only_regressors=False
)

rdk_task_motion_m1_idata = rdk_task_motion_m1.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'rdk_task_motion_m1.db', db = 'pickle')
rdk_task_motion_m1.save('rdk_task_motion_m1.hddm')

In [21]:
# 只筛选出不含"_subj."的参数行
summary = az.summary(rdk_task_motion_m1_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                            mean     sd  hdi_3%  hdi_97%  mcse_mean  mcse_sd
a                          1.300  0.020   1.261    1.336      0.000    0.000  \
a_std                      0.161  0.016   0.134    0.191      0.000    0.000
t                          0.488  0.018   0.457    0.522      0.000    0.000
t_std                      0.147  0.013   0.123    0.172      0.000    0.000
z_Intercept                0.495  0.003   0.490    0.500      0.000    0.000
z_Intercept_std            0.021  0.002   0.017    0.026      0.000    0.000
v_Intercept                0.655  0.044   0.574    0.738      0.001    0.001
v_Intercept_std            0.313  0.038   0.245    0.386      0.001    0.001
v_association[T.self]     -0.051  0.061  -0.168    0.062      0.001    0.001
v_association[T.self]_std  0.427  0.057   0.323    0.535      0.002    0.001

                           ess_bulk  ess_tail  r_hat
a                            3444.0    4488.0   1.00
a_std                        3148.0    4057.0   1.00
t                            4436.0    4120.0   1.00
t_std                        3853.0    4241.0   1.00
z_Intercept                  2586.0    4221.0   1.00
z_Intercept_std              1939.0    2744.0   1.00
v_Intercept                  2405.0    4139.0   1.00
v_Intercept_std              1079.0    2524.0   1.01
v_association[T.self]        2014.0    3766.0   1.00
v_association[T.self]_std     791.0    1734.0   1.01

### m2: v随association和difficulty变化

In [ ]:
data_motion_rdk['response'] = data_motion_rdk['correct']

# 定义链接函数
def z_link_func(x, data=data_motion_rdk):
    stim = data.stim.loc[x.index]
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip
    
# 构建回归模型
model_reg = [
    {'model': "z ~ 1", 'link_func': z_link_func},
    {'model': "v ~ 1 + association*difficulty", 'link_func': lambda x: x}
] 
 
rdk_task_motion_m2 = hddm.HDDMRegressor(
    data_motion_rdk,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    # depends_on={'z': ['association']},
    group_only_regressors=False
)

rdk_task_motion_m2_idata = rdk_task_motion_m2.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'rdk_task_motion_m2.db', db = 'pickle')
rdk_task_motion_m2.save('rdk_task_motion_m2.hddm')

In [ ]:
# 只筛选出不含"_subj."的参数行
summary = az.summary(rdk_task_motion_m2_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

### 模型比较

In [ ]:
DIC_dict = {
    "m0": rdk_task_motion_m0.dic,
    "m1": rdk_task_motion_m1.dic,
    "m2": rdk_task_motion_m2.dic,
}

DIC_table = pd.DataFrame.from_dict(DIC_dict, orient="index", columns=["DIC"])
DIC_table["model"] = DIC_table.index
DIC_table = DIC_table[["model", "DIC"]]
DIC_table.sort_values(by=["DIC"], ascending=False)

   model           DIC
m1    m1  15242.165691
m2    m2  14909.011104

## 颜色组辨别任务
- m0：基础模型
- m1: v随association变化
- m2：v随association和difficulty变化

### m0

In [ ]:
data_color_rdk['response'] = data_color_rdk['correct']

# 定义链接函数
def z_link_func(x, data=data_color_rdk):
    stim = data.stim.loc[x.index]
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip
    
# 构建回归模型
model_reg = [
    {'model': "z ~ 1", 'link_func': z_link_func},
    {'model': "v ~ 1", 'link_func': lambda x: x}
] 
 
rdk_task_color_m0 = hddm.HDDMRegressor(
    data_color_rdk,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    # depends_on={'z': ['association']},
    group_only_regressors=False
)

rdk_task_color_m0_idata = rdk_task_color_m0.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'rdk_task_color_m0.db', db = 'pickle')
rdk_task_color_m0.save('rdk_task_color_m0.hddm')

In [ ]:
# 只筛选出不含"_subj."的参数行
summary = az.summary(rdk_task_color_m0_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

### m1：v随association变化

In [ ]:
data_color_rdk['response'] = data_color_rdk['correct']

# 定义链接函数
def z_link_func(x, data=data_color_rdk):
    stim = data.stim.loc[x.index]
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip
    
# 构建回归模型
model_reg = [
    {'model': "z ~ 1", 'link_func': z_link_func},
    {'model': "v ~ 1 + association", 'link_func': lambda x: x}
] 
 
rdk_task_color_m1 = hddm.HDDMRegressor(
    data_color_rdk,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    # depends_on={'z': ['association']},
    group_only_regressors=False
)

rdk_task_color_m1_idata = rdk_task_color_m1.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'rdk_task_color_m1.db', db = 'pickle')
rdk_task_color_m1.save('rdk_task_color_m1.hddm')

In [32]:
# 只筛选出不含"_subj."的参数行
summary = az.summary(rdk_task_color_m1_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                            mean     sd  hdi_3%  hdi_97%  mcse_mean  mcse_sd
a                          1.329  0.023   1.287    1.373      0.000    0.000  \
a_std                      0.179  0.017   0.148    0.212      0.000    0.000
t                          0.500  0.015   0.473    0.528      0.000    0.000
t_std                      0.124  0.012   0.104    0.147      0.000    0.000
z_Intercept                0.467  0.008   0.451    0.482      0.000    0.000
z_Intercept_std            0.063  0.006   0.051    0.075      0.000    0.000
v_Intercept                1.061  0.051   0.964    1.157      0.001    0.001
v_Intercept_std            0.376  0.044   0.295    0.456      0.001    0.001
v_association[T.self]     -0.008  0.095  -0.185    0.169      0.002    0.001
v_association[T.self]_std  0.733  0.078   0.589    0.879      0.002    0.001

                           ess_bulk  ess_tail  r_hat
a                            3442.0    3652.0    1.0
a_std                        2946.0    4015.0    1.0
t                            4551.0    4348.0    1.0
t_std                        3757.0    3081.0    1.0
z_Intercept                  3346.0    4824.0    1.0
z_Intercept_std              1997.0    3243.0    1.0
v_Intercept                  2326.0    4337.0    1.0
v_Intercept_std              1091.0    2466.0    1.0
v_association[T.self]        2957.0    4882.0    1.0
v_association[T.self]_std    1398.0    2533.0    1.0

### m2

In [ ]:
data_color_rdk['response'] = data_color_rdk['correct']

# 定义链接函数
def z_link_func(x, data=data_color_rdk):
    stim = data.stim.loc[x.index]
    z_flip = (stim * x) + (1 - x) * (1 - stim)
    return z_flip
    
# 构建回归模型
model_reg = [
    {'model': "z ~ 1", 'link_func': z_link_func},
    {'model': "v ~ 1 + association*difficulty", 'link_func': lambda x: x}
] 
 
rdk_task_color_m2 = hddm.HDDMRegressor(
    data_color_rdk,
    model_reg,
    bias=True,
    include=['v', 'a', 't', 'z'],
    # depends_on={'z': ['association']},
    group_only_regressors=False
)

rdk_task_color_m2_idata = rdk_task_color_m2.sample(5000, burn=1000, chains=4, return_infdata=True, dbname = 'rdk_task_color_m2.db', db = 'pickle')
rdk_task_color_m2.save('rdk_task_color_m2.hddm')

In [5]:
# 只筛选出不含"_subj."的参数行
summary = az.summary(rdk_task_color_m2_idata)
group_params = summary[~summary.index.str.contains('_subj.')]
print(group_params)

                                       mean     sd  hdi_3%  hdi_97%
a                                     1.365  0.024   1.322    1.411  \
a_std                                 0.192  0.018   0.159    0.227
t                                     0.499  0.015   0.471    0.526
t_std                                 0.124  0.012   0.103    0.146
z_Intercept                           0.465  0.008   0.449    0.481
z_Intercept_std                       0.065  0.007   0.053    0.077
v_Intercept                           2.396  0.079   2.253    2.546
v_Intercept_std                       0.435  0.055   0.339    0.539
v_association[T.self]                -0.021  0.131  -0.262    0.225
v_association[T.self]_std             0.804  0.088   0.647    0.972
v_difficulty                         -0.498  0.022  -0.540   -0.457
v_difficulty_std                      0.074  0.018   0.039    0.108
v_association[T.self]:difficulty      0.006  0.032  -0.064    0.061
v_association[T.self]:difficulty_std  0.079  0.035   0.007    0.136

                                      mcse_mean  mcse_sd  ess_bulk  ess_tail
a                                         0.000    0.000    3872.0    4169.0  \
a_std                                     0.000    0.000    3215.0    3938.0
t                                         0.000    0.000    4808.0    3903.0
t_std                                     0.000    0.000    4256.0    3648.0
z_Intercept                               0.000    0.000    3243.0    4851.0
z_Intercept_std                           0.000    0.000    2255.0    3672.0
v_Intercept                               0.006    0.004     164.0     638.0
v_Intercept_std                           0.002    0.001     689.0    1749.0
v_association[T.self]                     0.010    0.007     163.0     347.0
v_association[T.self]_std                 0.003    0.002     846.0    1543.0
v_difficulty                              0.002    0.002     108.0     294.0
v_difficulty_std                          0.002    0.001      96.0     270.0
v_association[T.self]:difficulty          0.003    0.002      89.0     125.0
v_association[T.self]:difficulty_std      0.007    0.005      22.0      14.0

                                      r_hat
a                                      1.00
a_std                                  1.00
t                                      1.00
t_std                                  1.00
z_Intercept                            1.00
z_Intercept_std                        1.00
v_Intercept                            1.03
v_Intercept_std                        1.01
v_association[T.self]                  1.02
v_association[T.self]_std              1.01
v_difficulty                           1.04
v_difficulty_std                       1.06
v_association[T.self]:difficulty       1.04
v_association[T.self]:difficulty_std   1.14

### 模型比较

In [ ]:
# rdk_task_color_m1 = hddm.load('rdk_task_color_m1.hddm')
# rdk_task_color_m2 = hddm.load('rdk_task_color_m2.hddm')

In [ ]:
DIC_dict = {
    "m0": rdk_task_color_m0.dic,
    "m1": rdk_task_color_m1.dic,
    "m2": rdk_task_color_m2.dic,
}

DIC_table = pd.DataFrame.from_dict(DIC_dict, orient="index", columns=["DIC"])
DIC_table["model"] = DIC_table.index
DIC_table = DIC_table[["model", "DIC"]]
DIC_table.sort_values(by=["DIC"], ascending=False)

   model           DIC
m1    m1  12874.968865
m2    m2  11502.421202